#!/usr/bin/env python3

import kafkautils
import subprocess

from charmhelpers.core import hookenv, host
from charms.reactive import is_state
from jujubigdata.utils import run_as


if not is_state('kafka.started'):
    kafkautils.fail('Kafka service not yet ready')


# Grab the business
topic_name = hookenv.action_get('topic')
topic_partitions = hookenv.action_get('partitions')
topic_replication = hookenv.action_get('replication')

# Create the topic if kafka is running
if host.service_available('kafka') and host.service_running('kafka'):
    zookeepers = kafkautils.get_zookeepers()
    try:
        output = run_as('kafka', 'kafka-topics.sh',
                        '--zookeeper', zookeepers, '--create',
                        '--topic', topic_name,
                        '--partitions', topic_partitions,
                        '--replication-factor', topic_replication,
                        capture_output=True)
    except subprocess.CalledProcessError as e:
        kafkautils.fail('Kafka command failed', e.output)
    else:
        hookenv.action_set({'output': output})
else:
    kafkautils.fail('Kafka service is not running')
