#!/usr/bin/env python3
import sys
import kafkautils

try:
    from charmhelpers.core import host
    from charmhelpers.core import hookenv
    charm_ready = True
except ImportError:
    charm_ready = False

if not charm_ready:
    # might not have hookenv.action_fail available yet
    from subprocess import call
    call(['action-fail', 'Kafka service not yet ready'])
    sys.exit(1)

if host.service_available('kafka') and host.service_running('kafka'):
    zookeepers = kafkautils.get_zookeepers()
    hookenv.action_set({'zookeepers': zookeepers})
    # hookenv.action_set('outcome', "success")
    sys.exit(0)
else:
    hookenv.action_fail('Zookeeper relation is not present/ready')
    sys.exit(1)
