#!/usr/bin/env python3
import sys
import kafkautils

try:
    from charmhelpers.core import host
    from charmhelpers.core import hookenv
    from charmhelpers.core import unitdata
    from jujubigdata import utils
    charm_ready = True
except ImportError:
    charm_ready = False

if not charm_ready:
    # might not have hookenv.action_fail available yet
    from subprocess import call
    call(['action-fail', 'Kafka service not yet ready'])

if host.service_available('kafka') and host.service_running('kafka'):
    zookeepers = kafkautils.get_zookeepers()
    output = utils.run_as('kafka', '/usr/lib/kafka/bin/kafka-topics.sh',
                          '--zookeeper', zookeepers, '--list',
                          capture_output=True)
    hookenv.action_set({'topics': output})
    sys.exit(0)
else:
    hookenv.action_fail('Zookeeper relation is not present/ready')
    sys.exit(1)
