#!/usr/bin/env python3

import kafkautils

from charmhelpers.core import hookenv, host
from charms.reactive import is_state


if not is_state('kafka.started'):
    kafkautils.fail('Kafka service not yet ready')


# List zookeepers if kafka is running
if host.service_available('kafka') and host.service_running('kafka'):
    zookeepers = kafkautils.get_zookeepers()
    if zookeepers:
        hookenv.action_set({'output': zookeepers})
    else:
        kafkautils.fail('No zookeeper.connect string found')
else:
    kafkautils.fail('Kafka service is not running')
