#!/usr/bin/env python3

import kafkautils
import subprocess

from charmhelpers.core import hookenv, host
from charms.reactive import is_state
from jujubigdata.utils import run_as


if not is_state('kafka.started'):
    kafkautils.fail('Kafka service not yet ready')


# List topics if kafka is running
if host.service_available('kafka') and host.service_running('kafka'):
    zookeepers = kafkautils.get_zookeepers()
    try:
        output = run_as('kafka', '/usr/lib/kafka/bin/kafka-topics.sh',
                        '--zookeeper', zookeepers, '--list',
                        capture_output=True)
    except subprocess.CalledProcessError as e:
        kafkautils.fail('Kafka command failed', e.output)
    else:
        hookenv.action_set({'output': output})
else:
    kafkautils.fail('Kafka service is not running')
