#!/usr/bin/env python3
#pylint: disable=C0103
import sys

try:
    from charmhelpers.core import hookenv
    from jujubigdata import utils
    charm_ready = True
except ImportError:
    charm_ready = False

if not charm_ready:
    # might not have hookenv.action_fail available yet
    from subprocess import call
    call(['action-fail', 'Kafka service not yet ready'])
    sys.exit(1)

# Grab the business
topic_name = hookenv.action_get('topic')
topic_partition = hookenv.action_get('partition')

output = utils.run_as(
    'kafka', 'kafka-simple-consumer-shell.sh',
    '--broker-list', '{}:{}'.format(
        hookenv.unit_get('public-address'),
        utils.DistConfig().port('kafka'),
    ),
    '--topic', topic_name,
    '--partition', topic_partition,
    '--no-wait-at-logend',
    capture_output=True)
hookenv.action_set({'output': output})
sys.exit(0)
