#!/usr/bin/env python3

import kafkautils
import subprocess

from charmhelpers.core import hookenv, host
from charms.reactive import is_state
from jujubigdata import utils


if not is_state('kafka.started'):
    kafkautils.fail('Kafka service not yet ready')


# Grab the business
topic_name = hookenv.action_get('topic')
topic_partition = hookenv.action_get('partition')

# Read the topic if kafka is running
if host.service_available('kafka') and host.service_running('kafka'):
    host = subprocess.check_output(['hostname', '-s']).decode('utf8').strip()
    port = utils.DistConfig().port('kafka')
    zookeepers = kafkautils.get_zookeepers()
    try:
        output = utils.run_as('kafka', 'kafka-simple-consumer-shell.sh',
                              '--broker-list', '{}:{}'.format(host, port),
                              '--topic', topic_name,
                              '--partition', topic_partition,
                              '--no-wait-at-logend',
                              capture_output=True)
    except subprocess.CalledProcessError as e:
        kafkautils.fail('Kafka command failed', e.output)
    else:
        hookenv.action_set({'output': output})
else:
    kafkautils.fail('Kafka service is not running')
