#!/usr/bin/env python3
#pylint: disable=C0103
import sys

try:
    from charmhelpers.core import hookenv
    from jujubigdata import utils
    charm_ready = True
except ImportError:
    charm_ready = False

if not charm_ready:
    # might not have hookenv.action_fail available yet
    from subprocess import call
    call(['action-fail', 'Kafka service not yet ready'])
    sys.exit(1)

# Grab the business
topic_name = hookenv.action_get('topic')
data = hookenv.action_get('data')

output = utils.run_as(
    'kafka', 'kafka-console-producer.sh',
    '--broker-list', '{}:{}'.format(
        hookenv.unit_get('public-address'),
        utils.DistConfig().port('kafka'),
    ),
    '--topic', topic_name,
    capture_output=True,
    input=bytes(data, 'UTF-8'))
hookenv.action_set({'output': output})
sys.exit(0)
